import { db, Facilitators } from 'astro:db';

export default async function() {
  await db.insert(Facilitators).values([
	{
	  id: '1',
	  createdDate: new Date(),
	  updatedDate: new Date(),
	  firstName: 'Debbie',
	  lastName: 'Holcomb',
	  email: 'debbie.holcomb@gmail.com',
	  languages: 'English',
	  country: 'United States',
	  timeZone: 'America/Central',
	  location: 'Rockford, Illinois',
	  website: 'https://Debbieholcomb.com',
	  yearsOfExperience: '20',
	  areasOfExpertise: "Shadow Work, breath-work , bio-energetic work , communication, gender differences, relationships, conflict/resolution",
	  certifications: 'Shadow work . Shadow type profiling. Basic facilitator training. Advanced facilitator training. Couples coaching. Group Leadership training',
	  fees: '3000/day',
	  programOffered: 'Retreats, individual coaching. Family retreats. Personality profiling. Basic Facilitator Training. Advanced Facilitator Training. Forum group leadership.',
	  clientList: 'None',
	  status: 'active'
	},
	{
	  id: '2',
	  createdDate: new Date(),
	  updatedDate: new Date(),
	  firstName: 'James',
	  lastName: 'Gallagher',
	  email: 'jgallagher@psasecurity.com',
	  languages: 'English',
	  country: 'United States',
	  timeZone: 'America/Central',
	  location: 'Westminster, CO',
	  website: 'https://psasecurity.com/',
	  yearsOfExperience: '3',
	  areasOfExpertise: 'Communication, Relationship Building, Collaboration Solutions, Meeting Facilitation',
	  certifications: 'IFO Certified Facilitator',
	  fees: 'TBD',
	  programOffered: '',
	  clientList: 'PSA Business Technology, PSA Cybersecurity Committee, PSA Emerging Technology Committee, PSA Finance & Accounting Committee, PSA Leadership Committee, PSA Managed Services Committee,  PSA Marketing Committee, PSA Next Generation Leadership Committee',
	  status: 'active'
	},
	{
	  id: '3',
	  createdDate: new Date(),
	  updatedDate: new Date(),
	  firstName: 'Stephanie',
	  lastName: 'Ford',
	  email: 'sford@warrenwhitney.com',
	  languages: 'English, Spanish',
	  country: 'United States',
	  timeZone: 'America/New_York',
	  location: 'Richmond, VA',
	  website: 'https://warrenwhitney.com/stephanie-ford/',
	  yearsOfExperience: '25',
	  areasOfExpertise: 'Strategic Planning, Succession Planning, Financing, Marketing, Business Development, Board Governance, Business Strategy',
	  certifications: 'IFO Certified Facilitator, Six Sigma Green Belt',
	  fees: 'TBD',
	  programOffered: 'Strategic Planning, Meeting/Group Facilitation, Succession Planning, Executive Coaching, Board Development',
	  clientList: 'Virginia Council of CEOs and others upon request.',
	  status: 'active'
	},
	{
	  id: '4',
	  createdDate: new Date(),
	  updatedDate: new Date(),
	  firstName: 'Paul E.',
	  lastName: 'Berman',
	  email: 'paul@id8strategies.com',
	  languages: 'English, Gestalt',
	  country: 'United States',
	  timeZone: 'America/Central',
	  location: 'Philadelphia, PA or Denver, CO',
	  website: '',
	  yearsOfExperience: '19',
	  areasOfExpertise: 'Communication, Relationship Building, Collaboration Solutions, Meeting Facilitation',
	  certifications: 'IFO Certified Facilitator',
	  fees: 'Coaching/Consulting from $1000/month, Live Peer Groups $1500-$2500 depending on amount of time, Retreats - customized depending on level of support desired. From complete retreat planning & execution to partial or full facilitation.',
	  programOffered: '',
	  clientList: 'ID8 Strategies',
	  status: 'active'
	}
  ]);
}