import { db, Facilitators } from 'astro:db';

export default async function() {
  await db.insert(Facilitators).values([
	{
      id: '1',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Paul',
      lastName: 'Berman',
      email: 'paul@id8strategies.com',
      languages: 'English, Gestalt',
      country: 'USA',
      location: 'Philadelphia or Colorado',
      website: 'https://www.id8strategies.com',
      yearsOfExperience: '19',
      areasOfExpertise: 'Peer Group & Retreat Facilitation, Business Coaching, and Consulting,',
      certifications: 'IFO',
      fees: 'Coaching/Consulting from $1000/month, Live Peer Groups $1500-$2500 depending on amount of time, Retreats - customized depending on level of support desired. From complete retreat planning & execution to partial or full facilitation.',
      programsOffered: 'Most of my programs are customized based on the needs of client / Company, offer complimentary \"good fit\" call or calls to determine fit and needs.',
      clientList: 'Do not disclose under confidentiality.',
      status: 'Active'
    },
    {
      id: '2',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Debbie',
      lastName: 'Holcomb',
      email: 'debbie.holcomb@gmail.com',
      languages: 'English',
      country: 'USA',
      timezone: 'CST',
      location: 'Rockford, Illinois',
      website: 'https://Debbieholcomb.com',
      yearsOfExperience: '20',
      areasOfExpertise: 'Shadow Work, breath-work , bio-energetic work , communication, gender differences, relationships, conflict/resolutionn',
      certifications: 'Shadow work . Shadow type profiling. Basic facilitator training. Advanced facilitator training. Couples coaching. Group Leadership training',
      fees: '$3000 per day.',
      programsOffered: 'Retreats, individual coaching. Family retreats. Personality profiling. Basic Facilitator Training. Advanced Facilitator Training. Forum group leadership.',
      clientList: 'Yes',
      status: 'Pending'
    },
    {
      id: '3',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Stephanie',
      lastName: 'Ford',
      email: 'sford@warrenwhitney.com',
      languages: 'English',
      country: 'USA',
      location: 'Richmond, VA',
      website: 'https://warrenwhitney.com/stephanie-ford/',
      yearsOfExperience: '25',
      areasOfExpertise: 'Strategic Planning, Succession Planning, Financing, Marketing, Business Development, Board Governance, Business Strategy',
      certifications: 'IFO Certified Facilitator, Six Sigma Green Belt',
      fees: 'Fee structure to be determined after review of engagement details including scope, timing, and location.',
      programsOffered: 'Strategic Planning, Meeting/Group Facilitation, Succession Planning, Executive Coaching, Board Development',
      clientList: 'Virginia Council of CEOs and others upon request.',
      status: 'Active'
    },
    {
      id: '4',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'James',
      lastName: 'Gallagher',
      email: 'jgallagher@psasecurity.com',
      languages: 'English',
      country: 'USA',
      timezone: 'CST',
      location: 'Westminster, CO',
      website: 'https://psasecurity.com/',
      yearsOfExperience: '3',
      areasOfExpertise: 'Communication, Relationship Building, Collaboration Solutions, Meeting Facilitation',
      certifications: 'IFO Certified Facilitator',
      fees: 'TBD',
      clientList: 'PSA Business Technology, PSA Cybersecurity Committee, PSA Emerging Technology Committee, PSA Finance & Accounting Committee, PSA Leadership Committee, PSA Managed Services Committee,  PSA Marketing Committee, PSA Next Generation Leadership Committee, PSA',
      status: 'Active'
    },
    {
      id: '5',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Atieno',
      lastName: 'Bird',
      email: 'atieno@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'Crozet, VA',
      website: 'https://atienobird.com',
      yearsOfExperience: '30',
      areasOfExpertise: 'Morale; Engagement; Retention; Inclusion Culture and Psychological Safety; Team Cohesion; Fluid Collaboration; Mission Alignment, and Leadership Development',
      certifications: 'Certified Psychodramatist (CP); Coaches Training Institute Certified Coach (CPCC); International Coaching Federation Certified Coach (PCC); Yoga Instructor per Don and Amba Stapleton (CYI); trained in Appreciative Inquiry with Jane Macgruder Watkins and M',
      fees: 'Program-dependent',
      programsOffered: 'Culture and leadership solutions through experiential learning events; curated retreats; peer exchange group facilitation, and executive coaching.',
      clientList: 'World Bank, NASA, FEMA, GSA, the SBA, Accenture, Adventist Health, police departments, public service agencies, hospitals, schools, and nonprofits; has coached over 250 private clients.',
      status: 'Active'
    },
    {
      id: '6',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Yuval',
      lastName: 'Yeret',
      email: 'yuval@yeretagility.com',
      languages: 'English, Hebrew',
      country: 'USA',
      location: 'Boston',
      website: 'https://yuvalyeret.com',
      yearsOfExperience: '31',
      areasOfExpertise: 'Organizational Agility, Product Development, Team and Organizational Coaching, Agile Leadership, OKRs, Strategic Alignment, Scaling',
      certifications: 'SAFe SPCT, SAFe Fellow, Professional Scrum Trainer',
      programsOffered: '',
      clientList: 'Biogen, BioMarin, Dyno Therapeutics, P&G, Gillette, CME Group, M:M Bio',
      status: 'Active'
    },
    {
      id: '7',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Jessie',
      lastName: 'Spressart',
      email: 'jessie@optiaconsulting.com',
      languages: 'English',
      country: 'USA',
      location: 'Miami, FL',
      website: 'https://www.optiaconsulting.com',
      yearsOfExperience: '20',
      areasOfExpertise: 'Management & Leadership, Mental Health & Well-being, Coaching, Mindfulness',
      certifications: 'International Coach Federation (ACC), Mental Health First Aid Instructor, MBTI, DISC, Hogan Leadership, ACE Certified Coach',
      fees: 'Dependent on program',
      programsOffered: 'Dependent on needs',
      status: 'Active'
    },
    {
      id: '8',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Len',
      lastName: 'Siegal',
      email: 'lensiegal@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'Travels from Chicago',
      website: 'https://siegalstrategies.com/',
      yearsOfExperience: '20',
      areasOfExpertise: 'Strategic Planning, Conflict resolution, facilitating, moderating, coaching',
      certifications: 'International Facilitators Organization',
      fees: 'Per project',
      programsOffered: 'Available for coaching, planning, conflict resolution, facilitating, moderating',
      status: 'Active'
    },
    {
      id: '9',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'David',
      lastName: 'Ingram',
      email: 'David.Ingram@eosworldwide.com',
      languages: 'English',
      country: 'USA',
      timezone: 'EST',
      location: 'Virginia',
      website: 'https://www.eosworldwide.com/david-ingram',
      areasOfExpertise: 'Forum Facilitation, SBOs, Recruiting and Hiring',
      clientList: 'tbd',
      status: 'Active'
    },
    {
      id: '10',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Scot',
      lastName: 'McRoberts',
      email: 'smcroberts@vaceos.org',
      languages: 'English',
      country: 'USA',
      location: 'Richmond VA',
      website: 'https://www.vaceos.org',
      yearsOfExperience: '24',
      areasOfExpertise: 'Structure, care and feeding of successful peer roundtables.',
      certifications: 'MPA, IOM',
      fees: 'Negotiable',
      programsOffered: 'Consulting for peer roundtable programs. Ad-hoc roundtables for meetings or conferences.',
      status: 'Active'
    },
    {
      id: '11',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Christina',
      lastName: 'Chesseri',
      email: 'Cmchesseri@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'New Jersey',
      areasOfExpertise: 'Relationship Building and Meeting Facilitation',
      certifications: 'IFO Certified Facilitator',
      fees: 'TBD',
      programsOffered: 'Peer group training and facilitation.',
      status: 'Active'
    },
    {
      id: '12',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Kati',
      lastName: 'Jalali',
      email: 'katijalali@icloud.com',
      languages: 'English, Farsi',
      country: 'USA',
      location: 'Washington DC',
      website: 'https://www.happycinnamon.com',
      yearsOfExperience: '10',
      areasOfExpertise: 'Life & Transition Coaching, Leadership Development, Energy Leadership™ Master Practitioner, Energy Management, Wellness Strategist',
      certifications: 'MBA, Professional Coach, Energy Leadership™ Master Practitioner, Resilience Coach, Holistic Health Coach, Yoga Instructor, Six Sigma Process Excellence Black Belt',
      fees: 'Customized based on client needs and service.  Ten one-on-one 60-minute coaching sessions starting at $2450',
      programsOffered: 'Complementary consultation, Individual and group coaching sessions, Energy Leadership Index Assessment and debrief session, Customized sessions based on client needs, Workshops',
      status: 'Active'
    },
    {
      id: '13',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Nancy',
      lastName: 'Koleda',
      email: 'nancypkoleda@yahoo.com',
      languages: 'Dutch, English',
      country: 'Netherlands',
      timezone: 'CET',
      location: 'Amsterdam',
      website: 'https://www.linkedin.com/in/nancy-koleda-2349585/',
      yearsOfExperience: '25',
      areasOfExpertise: 'Entrepreneurship, Executive Search, Psychological Safety, Hiring at C-Level, Interviewing, Leadership Development, Peer Group Facilitation',
      certifications: 'IFO Certified Facilitator',
      fees: 'Fee structure to be determined after review of engagement details including scope, timing, and location.',
      programsOffered: 'Peer exchange group facilitation/Forum facilitation',
      status: 'Active'
    },
    {
      id: '14',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Roger',
      lastName: 'Lee',
      email: 'rogerlee1960@gmail.com',
      languages: 'Mandarin, English',
      country: 'Taiwan',
      timezone: 'EST +8',
      location: 'Taipei',
      yearsOfExperience: '13',
      areasOfExpertise: 'Coaching ; Leadership Development; Peer Group Facilitation',
      certifications: 'CFF 2009',
      fees: '1950',
      programsOffered: 'To be confirmed',
      status: 'Active'
    },
    {
      id: '15',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Jim',
      lastName: 'Randall',
      email: 'jim@autobahnconsultants.com',
      languages: 'English',
      country: 'USA',
      location: 'Cleveland, OH',
      website: 'https://www.autobahnconsultants.com',
      yearsOfExperience: '7',
      areasOfExpertise: 'Strategic planning, operational consulting, management team diligence, executive coaching, hiring and candidate assessments for lower middle market organizations.',
      certifications: 'IFO Certified Facilitator, MBA',
      fees: '5,000 - 10,000',
      programsOffered: 'Strategic planning consulting, management team event facilitation, management team diligence,  executive coaching.',
      status: 'Active'
    },
    {
      id: '16',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Brian',
      lastName: 'Costanzo',
      email: 'briankcostanzo@gmail.com',
      areasOfExpertise: 'leadership',
      status: 'Active'
    },
    {
      id: '17',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Lauren',
      lastName: 'Basler',
      email: 'lauren@consciousascent.com',
      languages: 'English, Spanish',
      country: 'USA, Spain',
      timezone: 'CST, CEST',
      location: 'Chicago, IL & Barcelona, Spain',
      website: 'https://www.consciousascent.com',
      yearsOfExperience: '3',
      areasOfExpertise: 'Team Facilitation and NLP Somatic Coaching',
      certifications: 'SpiralMethod Facilitator, IFO Facilitator, Currently pursuing ICF Certification',
      fees: 'Contact Directly',
      programsOffered: 'Executive Team Forums, Peer Exchange Forums, Strategic Planning Workshops, Leadership Development Workshops, 1:1 Coaching',
      status: 'Active'
    },
    {
      id: '18',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'John',
      lastName: 'Haydock',
      email: 'john@sightcastingllc.com',
      languages: 'English',
      country: 'USA',
      timezone: 'EST',
      location: 'Charlottesville Virginia',
      website: 'https://sightcastingconsulting.com',
      yearsOfExperience: '30',
      areasOfExpertise: 'Assessing personal, team, and organization mission, vision and values. Building high performing teams and culture. Strategic planning. Corporate and team retreats. Constructive feedback tools.',
      fees: '$300/hr. $2750/day. $1200 travel day plus expenses.',
      programsOffered: 'Meeting facilitation, executive coaching, conflict resolution, team building, establishing mission, vision, values.',
      clientList: 'Held leadership roles at Cadbury Schweppes, Burts Bees, Crutchfield, as well as President role at Plow and Hearth. Recent clients include Poppy Flowers, Runnymede, International Global Services, Beverage Tractor, Varnish Lane, Siglar Fishing, Starion Bank',
      status: 'Active'
    },
    {
      id: '19',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Leah',
      lastName: 'Litman',
      email: 'litmanleah@gmail.com',
      languages: 'English, Spanish',
      country: 'USA',
      timezone: 'EST',
      location: 'Washington D.C. / New Orleans',
      yearsOfExperience: '1',
      areasOfExpertise: 'Conflict Resolution, Leadership Development, Diversity and Inclusion, Decision Making, Creative Problem Solving, Team Building',
      certifications: 'IFO Certified Facilitator',
      fees: 'negotiable',
      programsOffered: 'peer group startup orientation, focus on starting peer groups within youth and college communities',
      clientList: 'younger communities ; startup',
      status: 'Pending'
    },
    {
      id: '21',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Jeff',
      lastName: 'Behrens',
      email: 'jeff@adviza.com',
      languages: 'English. French (conversant). A little Spanish.',
      country: 'USA',
      location: 'Boston and/or California',
      website: 'https://www.adviza.com',
      yearsOfExperience: '28',
      areasOfExpertise: 'Biotech, high tech, life sciences. Angel investing. Fundraising. Company sales/exits.',
      certifications: 'IFO. PhD',
      fees: 'TBD',
      programsOffered: 'Peer group training and facilitation. CEO coaching. Exit strategy prep and consulting.',
      status: 'Active'
    },
    {
      id: '22',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Tina',
      lastName: 'Sung',
      email: 'tinasung@comcast.net',
      languages: 'English',
      country: 'USA',
      location: 'Silver Spring MD',
      yearsOfExperience: '25',
      areasOfExpertise: 'Skilled Facilitation of Executive Groups; Governance; Non-profit and mid-market company growth strategies.',
      certifications: 'Certified International Facilitators Organization Facilitator; Certified Association Executive (CAE); National Association of Corporate Directors - Certified Director (NACD-DC)',
      fees: '$5000-$11,000 a day + travel and expenses',
      programsOffered: 'Skill Facilitation',
      status: 'Active'
    },
    {
      id: '23',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Rob',
      lastName: 'Wensing',
      email: 'rob@wensinggroup.com',
      languages: 'English',
      country: 'USA',
      timezone: 'PST',
      location: 'San Francisco',
      website: 'https://www.wensinggroup.com',
      yearsOfExperience: '20',
      areasOfExpertise: 'Training new groups/members; facilitating group meetings; planning and facilitating retreats; developing new peer group programs; facilitating strategic planning retreats for companies',
      certifications: 'MBA - University of Colorado. MS Management and Organization - University of Colorado. Certified Facilitator by International Facilitators Organization.',
      fees: 'Based on services',
      programsOffered: 'Training new groups/members; facilitating group meetings; planning and facilitating retreats; developing new peer group programs; facilitating company strategy and business planning  retreats',
      clientList: 'EO and YPO forums/members. Dropbox.',
      status: 'Active'
    },
    {
      id: '24',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Masha',
      lastName: 'Malka',
      email: 'masha@mashamalka.com',
      languages: 'English and Russian fluent. Spanish spoken',
      country: 'Spain, Central European',
      timezone: 'CEST',
      location: 'Malaga, Spain or London, UK',
      website: 'https://www.mashamalka.com',
      yearsOfExperience: '22',
      areasOfExpertise: 'Executive coaching, Change management, Emotional Mastery, Hypnotherapy, Women Empowerment,Motivational Speaking, Team meeting facilitation, Retreat facilitation',
      certifications: 'IFO Certification, The Science of Wellbeing, Accelerated Learning Techniques, NLP, EFT (Emotional Freedom Technique), Change Management, Transformational Thinking',
      fees: 'My fees are customized based on the clients objective',
      programsOffered: 'Change Management assessment, strategy and implementation. Year at a Glance Executive Coaching program. Emotional Mastery. Women in Leadership empowerment program.',
      clientList: 'ABN AMRO, ADB (Asian Development Bank), Xalq Bank (Uzbekistan), Shell Bulgaria, Inet Technologies, Mediacom',
      status: 'Active'
    },
    {
      id: '25',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Ed',
      lastName: 'Johnson',
      email: 'ed@craftedcoach.com',
      languages: 'English',
      country: 'USA',
      timezone: 'EST',
      location: 'Warrenton, VA (metro DC)',
      website: 'https://www.craftedcoach.com',
      yearsOfExperience: '15',
      areasOfExpertise: 'Facilitation, Coaching, Leadership/Personal/Professional Development, Motivational Speaking, Peer Learning Groups',
      certifications: 'International Coaching Federation Professional Certified Coach (PCC), Certified Positive Intelligence Mental Fitness Coach & Facilitator, Certified TetraMap® Facilitator, Credentialed in The Harrison Assessment',
      programsOffered: 'Positive Intelligence, TetraMap, Board Retreats, Individualized Workshops, Peer Learning Experiences, 1:1 Executive Coaching',
      status: 'Active'
    },
    {
      id: '26',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'EricaBeth',
      lastName: 'Koffler',
      email: 'ericabethkoffler@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'New York City',
      website: 'https://ConfidanteClub.com',
      areasOfExpertise: 'Retreats, Johari Window',
      status: 'Active'
    },
    {
      id: '27',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Rachael',
      lastName: 'Mizuno',
      email: 'rachael@swanzuno.com',
      languages: 'English',
      country: 'USA',
      location: 'Chicago, IL'
    },
    {
      id: '28',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Kimberly',
      lastName: 'Stietz',
      email: 'stietzk@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'Washington DC'
    },
    {
      id: '29',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Brian',
      lastName: 'Lunt',
      email: 'brianlunt@seedlevelstl.com',
      languages: 'English',
      country: 'USA'
    },
    {
      id: '30',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Angela',
      lastName: 'Momney',
      email: 'angela@momneyconsulting.com',
      languages: 'English',
      country: 'USA',
      location: 'Los Angeles, CA'
    },
    {
      id: '31',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Jennifer',
      lastName: 'Boyden',
      email: 'jenboyden10@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'Richmond, VA'
    },
    {
      id: '32',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Mark',
      lastName: 'Fenner',
      email: 'markf@risepg.com',
      languages: 'English',
      country: 'USA',
      location: 'Dallas, TX'
    },
    {
      id: '33',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Shayla',
      lastName: 'Alexander',
      email: 'shayla.alexander@shrm.org',
      languages: 'English',
      country: 'USA',
      location: 'Washington DC'
    },
    {
      id: '34',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Stacey',
      lastName: 'Lauren',
      email: 'stacey@dothethingformula.com',
      languages: 'English',
      country: 'USA',
      location: 'San Diego, CA'
    },
    {
      id: '35',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Lisa',
      lastName: 'Liguori',
      email: 'lisa.liguori@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'San Diego, CA'
    },
    {
      id: '36',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Ipek',
      lastName: 'Utun',
      email: 'ipek@ipekutun.com',
      languages: 'English, Turkish',
      country: 'USA',
      location: 'Irvine, CA'
    },
    {
      id: '37',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Hugo',
      lastName: 'Chou',
      email: 'hugo@thepartner.com.tw',
      languages: 'English',
      country: 'Taiwan',
      timezone: 'EST +8',
      location: 'Taipei'
    },
    {
      id: '38',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Hillary',
      lastName: 'Rovario',
      email: 'hillary@accp.org',
      languages: 'English',
      country: 'USA',
      location: 'Winter Park, FL'
    },
    {
      id: '39',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Erica',
      lastName: 'Young',
      email: 'erica.young@shrm.org',
      languages: 'English',
      country: 'USA',
      location: 'Alexandria, VA'
    },
    {
      id: '40',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Elisa',
      lastName: 'Garn',
      email: 'Elisa.garn@shrm.org',
      languages: 'English',
      country: 'USA',
      location: 'Salt Lake City, UT'
    },
    {
      id: '41',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Didrik',
      lastName: 'Etholm',
      email: 'didriketholm@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'Boston, MA'
    },
    {
      id: '42',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Anika',
      lastName: 'Dhir',
      email: 'anika.dhir@shrm.org',
      languages: 'English',
      country: 'USA',
      location: 'Alexandria, VA'
    },
    {
      id: '43',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Alexander',
      lastName: 'Pullen',
      email: 'alexander.pullen@shrm.org',
      languages: 'English',
      country: 'USA',
      location: 'Atlanta, GA'
    },
    {
      id: '44',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Ash',
      lastName: 'Shabudin',
      email: 'ash.shabudin@gmail.com',
      languages: 'English',
      country: 'USA',
      location: 'Washington, DC'
    },
    {
      id: '45',
      createdDate: new Date(),
      updatedDate: new Date(),
      firstName: 'Crystal',
      lastName: 'Yang',
      email: 'zimouqq@hotmail.com',
      languages: 'English',
      country: 'China',
      location: 'Shanghai'
    }
  ]);
}

